# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_identifier', models.CharField(max_length=512)),
                ('scheduled', models.DateTimeField(verbose_name='scheduled datetime')),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
